---
title: "snyder_proctor_creek"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Computational environment
========================================================
Location of this repository: 
https://github.com/puruckertom/snyder_proctor_creek


```{r eval=FALSE, echo=FALSE}
#library(installr) #windows only currently
#updateR()
```
Version and installed libraries.
```{r eval=TRUE, echo=TRUE}
R.Version()$version.string
Sys.info()[4]
```

```{r eval=TRUE, echo=FALSE}
library(ggplot2)
require(gridExtra)
library(reshape2)
## Including Plots

# tom mac
if(Sys.info()[4] == "Toms-Air"){
  pcdir <- path.expand("~/git/snyder_proctorcreek/")
}

pcdir_data_in <- paste(pcdir,'data_in/',sep='')
pcdir_data_out <- paste(pcdir,'data_out/',sep='')
pcdir_graphics <- paste(pcdir,'graphics/',sep='')
pcdir_src <- paste(pcdir,'src/',sep='')
```

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

Introduction
========================================================
Blake's data from x locations with x observations.

```{r cars}
pc_data_file <- paste(pcdir_data_in,"proctor_creek.csv", sep="")
file.exists(pc_data_file)
pc_data <- read.table(pc_data_file, header = TRUE, sep = ",")
dim(pc_data)
summary(pc_data)
```
